# Generated by Django 5.2.17 on 2026-08-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='modificado_en',
            field=models.DateTimeField(blank=True, help_text='Última edición (solo autor)', null=True),
        ),
    ]
