# Generated by Django 5.2.17 on 2026-08-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comentario_modificado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='estado_previo',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('CERRADO', 'Cerrado'), ('REABIERTO', 'Reabierto')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticketdesarrollador',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
