# Generated by Django 5.2.17 on 2026-08-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ticket_estado_previo_ticketdesarrollador_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
