# Generated by Django 5.2.17 on 2026-09-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comentario_eliminado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='prompt',
            field=models.TextField(blank=True, help_text='Descripción del sistema para el análisis IA (opcional)'),
        ),
    ]
