# Generated by Django 5.2.17 on 2026-09-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sistema_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloia',
            name='formato_salida',
            field=models.CharField(choices=[('RESPONSE_FORMAT', 'JSON mode (response_format) del endpoint OpenAI-compatible'), ('NATIVO', 'Formato nativo del proveedor (p.ej. Ollama: format: json)'), ('NINGUNO', 'Ninguno: se pide JSON por instrucción en el prompt')], default='RESPONSE_FORMAT', help_text='Cómo se le pide al modelo el JSON de salida', max_length=20),
        ),
    ]
