# Generated by Django 5.2.17 on 2026-09-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_modeloia_formato_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='modificado_en',
            field=models.DateTimeField(blank=True, help_text='Última edición (solo solicitante dueño)', null=True),
        ),
    ]
