# Generated by Django 5.2.17 on 2026-09-07 14:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ticket_eliminado_en_ticket_modificado_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjunto',
            name='archivo',
            field=models.FileField(upload_to=core.models._ruta_archivo_adjunto),
        ),
    ]
