# Generated by Django 5.2.17 on 2026-09-10 21:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_adjunto_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturaTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_lectura_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_usuarios', to='core.ticket')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lectura de ticket',
                'verbose_name_plural': 'Lecturas de tickets',
                'unique_together': {('usuario', 'ticket')},
            },
        ),
    ]
