"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import environ 
import os 


from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env() 
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

DATABASE_URL = env('DATABASE_URL')

# API keys de IA: las guardo en os.environ para que ai/providers.py las lea.
for _key in ('GROQ_API_KEY', 'GOOGLE_AI_API_KEY', 'OPENROUTER_API_KEY', 'NVIDIA_API_KEY'):
    _val = env(_key, default='')
    if _val:
        os.environ.setdefault(_key, _val)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY', default='django-insecure-9in9v6(l5)=)8bube3)v5at8lc)k-a7pp32tyb+8+c@0n64n81')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DJANGO_DEBUG', default=True)

# En produccion setear DJANGO_ALLOWED_HOSTS (p.ej. el dominio .onrender.com).
# En dev se admite cualquier host (advertencia: no usar en produccion).
# Default para Render: cualquier subdominio .onrender.com (ademas de los locales).
ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default=['*']) + ['.onrender.com', 'localhost', '127.0.0.1']

# Redirect de usuarios anónimos hacia nuestro login propio (/login/)
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'ticket_list'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'ai',
    'huey.contrib.djhuey',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.modo_filtro_cliente',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
     'default': env.db_url('DATABASE_URL')     
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_USER_MODEL = "core.Usuario"

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Archivos estaticos colectados (para produccion con Whitenoise)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Archivos subidos por usuarios (adjuntos)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Whitenoise sirve los estaticos colectados (produccion).
# IMPORTANTE: al definir STORAGES manualmente hay que incluir SIEMPRE la clave
# 'default' (storage de archivos subidos/FileField). Sin ella, Django lanza
# InvalidStorageError 'Could not find config for default' al guardar adjuntos.
# En DEBUG los adjuntos van al FileSystemStorage local (media/); en produccion
# a Supabase Storage (S3-compatible) para que sobrevivan a los redeploys.
if DEBUG:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
else:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "access_key": env('SUPABASE_ACCESS_KEY'),
                "secret_key": env('SUPABASE_SECRET_KEY'),
                "bucket_name": env('SUPABASE_BUCKET'),
                "endpoint_url": env('SUPABASE_ENDPOINT'),
                "default_acl": "private",
                "querystring_auth": True,
                "querystring_expire": 300,
                "file_overwrite": False,
                "signature_version": "s3v4",
                "region_name": env('SUPABASE_REGION', default='us-east-1'),
                "addressing_style": "path",
            },
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Feature-flag: filtrado client-side (demo) vs server-side (produccion)
# True  -> el navegador recibe todo el dataset del usuario y filtra en JS
# False -> vuelve a filtrar/paginar en el servidor (HTMX)
# Default True si no esta definido en el .env
MODO_FILTRO_CLIENTE = env.bool('MODO_FILTRO_CLIENTE', default=True)

# Logging: permite ver el traceback de los errores 500 en los logs (p.ej. Render).
# Sin esto, en DEBUG=False Django no imprime los tracebacks en consola.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}


# Cola de tareas (Huey) para la capa de IA (Fase 2).
# PostgresHuey usa la misma DB configurada arriba (DATABASE_URL) como broker,
# por lo que no hace falta duplicar la conexión ni levantar Redis.
# `immediate=True` ejecuta las tareas en el mismo request (síncrono): es la vía
# para la demo en Render free porque NO requiere correr un worker aparte (un
# worker consumiría otra instancia del plan gratuito). Para producción con
# background real, poner AI_IMMEDIATE=False y correr `huey_consumer` como worker.
HUEY = {
    'huey_class': 'huey.PostgresHuey',
    'name': 'incidencias',
    'immediate': env.bool('AI_IMMEDIATE', default=True),
    'utc': True,
}
